In [1]:
import glob
import pandas as pd
from tqdm import tqdm

In [2]:
data_path='./time_series_data/DemDiag'

In [3]:
org_geo_df=pd.read_csv(data_path+'/ORGANISATION_REFERENCE.csv')

In [4]:
org_geo_dict=dict(zip(org_geo_df['CCG_CODE'].tolist(), org_geo_df['CCG_GEOGRAPHY_CODE'].tolist()))

In [5]:
file_path=glob.glob(data_path+'/*.csv')

In [6]:
file_path=sorted(file_path)

In [7]:
del file_path[0]

In [8]:
demdiag1=pd.read_csv(file_path[0])

In [9]:
column_for_finaldf=list(set(demdiag1['GEOGRAPHY_CODE'].tolist()))
demdiag_df = pd.DataFrame(columns = column_for_finaldf)

In [10]:
demdiag_df

Empty DataFrame
Columns: [E38000194, E38000159, E38000153, E38000010, E38000177, E38000188, E38000205, E38000077, E38000156, E38000003, E38000028, E38000091, E38000209, E38000095, E38000050, E38000107, E38000021, E38000136, E38000101, E38000009, E38000059, E38000120, E38000141, E38000029, E38000076, E38000099, E38000082, E38000203, E38000124, E38000168, E38000079, E38000158, E38000185, E38000098, E38000129, E38000062, E38000122, E38000084, E38000144, E38000166, E38000169, E38000143, E38000083, E38000213, E38000161, E38000108, E38000089, E38000176, E38000038, E38000116, E38000048, E38000006, E38000192, E38000004, E38000104, E38000127, E38000032, E38000178, E38000052, E38000150, E38000151, E38000142, E38000005, E38000214, E38000118, E38000007, E38000042, E38000133, E38000119, E38000113, E38000199, E38000125, E38000069, E38000190, E38000180, E38000198, E38000157, E38000054, E38000068, E38000167, E38000163, E38000189, E38000097, E38000044, E38000019, E38000155, E38000181, E38000154, E38000033, E38000055, E38000024, E38000093, E38000026, E38000139, E38000027, E38000078, E38000145, E38000090, E38000149, E38000031, ...]
Index: []

[0 rows x 209 columns]

In [11]:
for i in range(len(file_path)):
    row_name=file_path[i].split('demdiag')[-1].split('.')[0]
    demdiag_df=demdiag_df.append(pd.Series(name=row_name,dtype='float64'))

In [12]:
demdiag_df

,E38000194,E38000159,E38000153,E38000010,E38000177,E38000188,E38000205,E38000077,E38000156,E38000003,...,E38000072,E38000071,E38000074,E38000035,E38000025,E38000046,E38000066,E38000081,E38000085,E38000193
201701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
row_name=file_path[0].split('demdiag')[-1].split('.')[0]
demdiag1=pd.read_csv(file_path[0])
columns_name=['GEOGRAPHY_CODE','Value','Measure']
demdiag1=demdiag1[columns_name]
value1=demdiag1.groupby(['GEOGRAPHY_CODE'])

In [15]:
row_name

'201701'

In [16]:
value1.get_group('E38000042')

  GEOGRAPHY_CODE  Value                                         Measure
0      E38000042      4                          ASIAN_OR_ASIAN_BRITISH
1      E38000042      0  BLACK_OR_AFRICAN_OR_CARIBBEAN_OR_BLACK_BRITISH
2      E38000042      2                 MIXED_OR_MULTIPLE_ETHNIC_GROUPS
3      E38000042    455                                     NOT_DEFINED
4      E38000042      2                              OTHER_ETHNIC_GROUP
5      E38000042    612                                           WHITE

In [17]:
row_name=file_path[1].split('demdiag')[-1].split('.')[0]
demdiag2=pd.read_csv(file_path[1])
columns_name=['GEOGRAPHY_CODE','Value','Measure']
demdiag2=demdiag2[columns_name]
value2=demdiag2.groupby(['GEOGRAPHY_CODE'])

In [18]:
value2.get_group('E38000042')

  GEOGRAPHY_CODE  Value                                         Measure
0      E38000042      4                          ASIAN_OR_ASIAN_BRITISH
1      E38000042      0  BLACK_OR_AFRICAN_OR_CARIBBEAN_OR_BLACK_BRITISH
2      E38000042      2                 MIXED_OR_MULTIPLE_ETHNIC_GROUPS
3      E38000042    455                                     NOT_DEFINED
4      E38000042      2                              OTHER_ETHNIC_GROUP
5      E38000042    614                                           WHITE

In [19]:
row_name

'201702'

In [20]:
row_name=file_path[2].split('demdiag')[-1].split('.')[0]
demdiag3=pd.read_csv(file_path[2])
columns_name=['GEOGRAPHY_CODE','Value','Measure']
demdiag3=demdiag3[columns_name]
value3=demdiag3.groupby(['GEOGRAPHY_CODE'])

In [21]:
row_name

'201703'

In [22]:
value2.get_group('E38000042')

  GEOGRAPHY_CODE  Value                                         Measure
0      E38000042      4                          ASIAN_OR_ASIAN_BRITISH
1      E38000042      0  BLACK_OR_AFRICAN_OR_CARIBBEAN_OR_BLACK_BRITISH
2      E38000042      2                 MIXED_OR_MULTIPLE_ETHNIC_GROUPS
3      E38000042    455                                     NOT_DEFINED
4      E38000042      2                              OTHER_ETHNIC_GROUP
5      E38000042    614                                           WHITE

In [13]:
for file in file_path:
    row_name=file.split('demdiag')[-1].split('.')[0]
    demdiag=pd.read_csv(file)
    columns_name=['GEOGRAPHY_CODE','Value']
    demdiag=demdiag[columns_name]
    value=demdiag.groupby(['GEOGRAPHY_CODE']).sum()
    for index,row in value.iterrows():
        demdiag_df.loc[row_name,index]=row['Value']

In [14]:
demdiag_df

,E38000194,E38000159,E38000153,E38000010,E38000177,E38000188,E38000205,E38000077,E38000156,E38000003,...,E38000221,E38000222,E38000223,E38000224,E38000225,E38000226,E38000227,E38000228,E38000229,E38000230
201701,1377,1989,1775,2426,2653,2500,2337,1990,2009,1689,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201702,1403,1971,1809,2564,2680,2494,2358,1953,1999,1691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201703,1442,2001,1832,2461,2671,2504,2371,1963,1986,1678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201704,1649,2036,1831,3056,2712,2513,2385,1967,2044,1707,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201705,1660,2132,1829,3029,2714,2520,2289,1960,1967,1662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201706,1668,NaN,1814,3041,2709,2626,2371,1979,1956,1709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201707,1681,NaN,1839,3033,2730,2652,2384,2001,1944,1729,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201708,1712,NaN,1839,3035,2727,2660,2425,2013,1962,1724,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201709,1706,NaN,1847,3028,2760,2687,2495,2058,1959,1720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201710,1710,NaN,1842,3035,2809,2714,2449,2108,1932,1701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201711,1731,NaN,1901,3091,2802,2760,2541,2102,1998,1724,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201712,1719,NaN,1830,3126,2802,2750,2536,2083,1987,1726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201801,1718,NaN,1850,3105,2773,2754,2526,2065,1961,1691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201802,1732,NaN,1853,3104,2804,2743,2531,2025,1954,1674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201803,1770,NaN,1849,3092,2794,2737,2532,2004,1959,NaN,...,3386.0,7435.0,4383.0,2790.0,6183.0,2279.0,1472.0,3571.0,NaN,NaN
201804,1726,NaN,1853,3065,2798,2726,2539,1985,1956,NaN,...,3310.0,7507.0,4392.0,2763.0,6157.0,2265.0,1477.0,3574.0,NaN,NaN
201805,1741,NaN,1863,3068,2812,2759,2566,1999,1964,NaN,...,3418.0,7440.0,4402.0,2787.0,6173.0,2259.0,1487.0,3574.0,NaN,NaN
201806,1766,NaN,1846,3117,2827,2763,2580,2053,1980,NaN,...,3493.0,7574.0,4402.0,2850.0,6223.0,2289.0,1594.0,3591.0,NaN,NaN
201807,1779,NaN,1866,3115,2828,2778,2585,2057,2000,NaN,...,3504.0,7500.0,4423.0,2796.0,6250.0,2326.0,1509.0,3621.0,NaN,NaN
201808,1796,NaN,1884,3101,2844,2805,2618,2059,2002,NaN,...,3526.0,7595.0,4446.0,2804.0,6291.0,2313.0,1511.0,3648.0,NaN,NaN
201809,1911,NaN,1877,3195,2856,2818,2653,2087,2022,NaN,...,3606.0,7648.0,4465.0,2820.0,6431.0,2337.0,1507.0,3640.0,NaN,NaN
201810,1891,NaN,1851,3214,2879,2786,2664,2188,2009,NaN,...,3600.0,7642.0,4450.0,2818.0,6429.0,2332.0,1495.0,3670.0,NaN,NaN
201811,1885,NaN,1867,3247,2878,2796,2663,2211,2015,NaN,...,3639.0,7532.0,4481.0,2854.0,6447.0,2357.0,1492.0,3665.0,NaN,NaN
201812,1890,NaN,1858,3249,2886,2779,2662,2211,2014,NaN,...,3627.0,7574.0,4468.0,2847.0,6466.0,2355.0,1496.0,3671.0,NaN,NaN
201901,1907,NaN,1851,3230,2880,2755,2650,2217,2014,NaN,...,3610.0,7595.0,4432.0,2849.0,6429.0,2354.0,1522.0,3683.0,NaN,NaN
201902,1887,NaN,1871,3235,2874,2741,2610,2238,2024,NaN,...,3623.0,7593.0,4430.0,2735.0,6383.0,2358.0,1550.0,3673.0,NaN,NaN
201903,1899,NaN,1910,3278,2916,2736,2669,2335,2024,NaN,...,3651.0,7697.0,4480.0,2843.0,6425.0,2374.0,1572.0,3719.0,NaN,NaN
201904,1885,NaN,1888,3295,2931,2717,2689,2345,2057,NaN,...,3628.0,7676.0,4489.0,2837.0,6403.0,2356.0,1594.0,3714.0,9777.0,11456.0
201905,1881,NaN,1890,3330,2960,2708,2718,2361,2011,NaN,...,3624.0,7691.0,4521.0,2868.0,6333.0,2345.0,1606.0,3746.0,9835.0,11552.0
201906,1887,NaN,1927,3396,2965,2702,2731,2255,2017,NaN,...,3631.0,7758.0,4505.0,2891.0,6400.0,2344.0,1614.0,3764.0,9907.0,11719.0
201907,1912,NaN,1956,3476,2992,2704,2735,2232,2042,NaN,...,3681.0,7798.0,4555.0,2905.0,6436.0,2363.0,1627.0,3797.0,9938.0,11661.0
201908,1932,NaN,1986,3493,3026,2726,2771,2226,2061,NaN,...,3698.0,7883.0,4603.0,2914.0,6505.0,2358.0,1642.0,3837.0,19904.0,11741.0
201909,1941,NaN,1986,3538,3043,2712,2770,2222,2065,NaN,...,3714.0,8009.0,4574.0,2964.0,6546.0,2342.0,1640.0,3840.0,9993.0,11791.0
201910,1943,NaN,1950,3564,3011,2730,2750,2176,2064,NaN,...,3670.0,7833.0,4527.0,2917.0,6562.0,2312.0,1624.0,3787.0,10017.0,11779.0
201911,1948,NaN,1964,3563,3010,2726,2759,2181,2060,NaN,...,3684.0,7868.0,4543.0,2921.0,6547.0,2295.0,1628.0,3776.0,10006.0,11782.0
201912,1937,NaN,1959,3578,2998,2720,2746,2160,2055,NaN,...,3698.0,7827.0,4522.0,2898.0,6523.0,2277.0,1624.0,3740.0,9923.0,11763.0
202001,1942,NaN,1949,3560,2971,2723,2730,2150,2073,NaN,...,3695.0,7836.0,4511.0,2872.0,6509.0,2247.0,1639.0,3719.0,9870.0,11629.0

In [15]:
demdiag_df.to_csv('DementiaDiagnosis.csv',index=True)

In [16]:
pd.read_csv(file_path[0])

,ACH_DATE,COMMISSIONER_ORGANISATION_CODE,GEOGRAPHY_CODE,CCG_NAME,Measure,Value
0,31/01/2017,00C,E38000042,NHS Darlington CCG,ASIAN_OR_ASIAN_BRITISH,4
1,31/01/2017,00C,E38000042,NHS Darlington CCG,BLACK_OR_AFRICAN_OR_CARIBBEAN_OR_BLACK_BRITISH,0
2,31/01/2017,00C,E38000042,NHS Darlington CCG,MIXED_OR_MULTIPLE_ETHNIC_GROUPS,2
3,31/01/2017,00C,E38000042,NHS Darlington CCG,NOT_DEFINED,455
4,31/01/2017,00C,E38000042,NHS Darlington CCG,OTHER_ETHNIC_GROUP,2
...,...,...,...,...,...,...
1249,31/01/2017,99Q,E38000152,NHS South Devon and Torbay CCG,BLACK_OR_AFRICAN_OR_CARIBBEAN_OR_BLACK_BRITISH,0
1250,31/01/2017,99Q,E38000152,NHS South Devon and Torbay CCG,MIXED_OR_MULTIPLE_ETHNIC_GROUPS,4
1251,31/01/2017,99Q,E38000152,NHS South Devon and Torbay CCG,NOT_DEFINED,2843
1252,31/01/2017,99Q,E38000152,NHS South Devon and Torbay CCG,OTHER_ETHNIC_GROUP,3
1253,31/01/2017,99Q,E38000152,NHS South Devon and Torbay CCG,WHITE,286

In [17]:
column_for_finaldf=list(set(demdiag1['GEOGRAPHY_CODE'].tolist()))
column_for_race=[]
for column in column_for_finaldf:
    column_for_race.append(column+'_B')
    column_for_race.append(column+'_A')
    column_for_race.append(column+'_W')
    column_for_race.append(column+'_M')
    column_for_race.append(column+'_O')
    column_for_race.append(column+'_N')

In [18]:
demdiag_race = pd.DataFrame(columns = column_for_race)

In [19]:
for file in tqdm(file_path):
    row_name=file.split('demdiag')[-1].split('.')[0]
    demdiag=pd.read_csv(file)
    columns_name=['GEOGRAPHY_CODE','Measure','Value','COMMISSIONER_ORGANISATION_CODE']
    demdiag=demdiag[columns_name]
    for index,row in demdiag.iterrows():
        try:
            letters=list(row['Measure'])
            demdiag_race.loc[row_name,row['GEOGRAPHY_CODE']+'_'+letters[0]]=row['Value']
        except TypeError:
            try:
                geo_code=org_geo_dict[row['COMMISSIONER_ORGANISATION_CODE']]
                letters=list(row['Measure'])
                demdiag_race.loc[row_name,geo_code+'_'+letters[0]]=row['Value']
            except KeyError:
                continue

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 37/37 [00:20<00:00,  1.84it/s]

In [20]:
demdiag_race

,E38000194_B,E38000194_A,E38000194_W,E38000194_M,E38000194_O,E38000194_N,E38000159_B,E38000159_A,E38000159_W,E38000159_M,...,E38000229_M,E38000229_N,E38000229_O,E38000229_W,E38000230_A,E38000230_B,E38000230_M,E38000230_N,E38000230_O,E38000230_W
201701,0,7,525,0,1,844,0,1,216,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201702,0,7,525,0,1,870,0,1,207,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201703,0,7,532,0,1,902,0,2,216,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201704,0,8,634,1,2,1004,0,2,221,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201705,0,8,627,1,2,1022,0,3,222,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201706,0,7,624,1,2,1034,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201707,0,7,623,1,2,1048,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201708,0,7,629,1,2,1073,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201709,0,7,616,1,2,1080,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201710,0,7,626,1,2,1074,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201711,0,7,630,1,2,1091,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201712,0,7,635,1,2,1074,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201801,0,7,630,1,2,1078,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201802,0,7,631,1,2,1091,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201803,0,7,665,0,2,1096,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201804,0,7,641,0,2,1076,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201805,0,8,641,0,2,1090,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201806,0,9,644,0,2,1111,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201807,0,9,644,0,2,1124,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201808,0,9,649,0,3,1135,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201809,0,9,683,0,3,1216,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201810,0,10,681,0,3,1197,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201811,0,10,678,0,3,1194,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201812,0,10,680,1,3,1196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201901,0,12,687,1,5,1202,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201902,0,11,666,1,6,1203,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201903,0,11,683,0,7,1198,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201904,0,12,675,0,7,1191,NaN,NaN,NaN,NaN,...,37.0,6193.0,139.0,3264.0,18.0,0.0,8.0,9862.0,24.0,1544.0
201905,0,11,676,0,7,1187,NaN,NaN,NaN,NaN,...,37.0,6217.0,142.0,3294.0,19.0,0.0,8.0,9925.0,24.0,1576.0
201906,0,11,676,1,7,1192,NaN,NaN,NaN,NaN,...,38.0,6251.0,146.0,3324.0,19.0,0.0,9.0,10068.0,23.0,1600.0
201907,0,11,690,1,7,1203,NaN,NaN,NaN,NaN,...,39.0,6223.0,150.0,3379.0,19.0,0.0,9.0,9987.0,23.0,1623.0
201908,0,11,696,1,7,1217,NaN,NaN,NaN,NaN,...,78.0,12440.0,304.0,6788.0,19.0,0.0,9.0,10055.0,24.0,1634.0
201909,0,11,689,1,7,1233,NaN,NaN,NaN,NaN,...,38.0,6217.0,161.0,3432.0,19.0,0.0,9.0,10067.0,24.0,1672.0
201910,0,12,693,1,7,1230,NaN,NaN,NaN,NaN,...,41.0,6203.0,163.0,3467.0,20.0,0.0,9.0,10043.0,24.0,1683.0
201911,0,12,695,1,6,1234,NaN,NaN,NaN,NaN,...,42.0,6169.0,163.0,3492.0,18.0,0.0,9.0,9994.0,27.0,1734.0
201912,0,12,693,1,6,1225,NaN,NaN,NaN,NaN,...,41.0,6099.0,159.0,3482.0,16.0,0.0,9.0,9946.0,26.0,1766.0
202001,0,12,689,1,6,1234,NaN,NaN,NaN,NaN,...,42.0,5989.0,155.0,3540.0,14.0,0.0,9.0,9845.0,26.0,1735.0

In [22]:
demdiag_race.to_csv('demdiag_race.csv',index=True)

In [21]:
demdiag_race

,E38000194_B,E38000194_A,E38000194_W,E38000194_M,E38000194_O,E38000194_N,E38000159_B,E38000159_A,E38000159_W,E38000159_M,...,E38000229_M,E38000229_N,E38000229_O,E38000229_W,E38000230_A,E38000230_B,E38000230_M,E38000230_N,E38000230_O,E38000230_W
201701,0,7,525,0,1,844,0,1,216,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201702,0,7,525,0,1,870,0,1,207,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201703,0,7,532,0,1,902,0,2,216,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201704,0,8,634,1,2,1004,0,2,221,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201705,0,8,627,1,2,1022,0,3,222,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201706,0,7,624,1,2,1034,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201707,0,7,623,1,2,1048,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201708,0,7,629,1,2,1073,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201709,0,7,616,1,2,1080,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201710,0,7,626,1,2,1074,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201711,0,7,630,1,2,1091,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201712,0,7,635,1,2,1074,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201801,0,7,630,1,2,1078,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201802,0,7,631,1,2,1091,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201803,0,7,665,0,2,1096,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201804,0,7,641,0,2,1076,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201805,0,8,641,0,2,1090,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201806,0,9,644,0,2,1111,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201807,0,9,644,0,2,1124,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201808,0,9,649,0,3,1135,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201809,0,9,683,0,3,1216,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201810,0,10,681,0,3,1197,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201811,0,10,678,0,3,1194,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201812,0,10,680,1,3,1196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201901,0,12,687,1,5,1202,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201902,0,11,666,1,6,1203,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201903,0,11,683,0,7,1198,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201904,0,12,675,0,7,1191,NaN,NaN,NaN,NaN,...,37.0,6193.0,139.0,3264.0,18.0,0.0,8.0,9862.0,24.0,1544.0
201905,0,11,676,0,7,1187,NaN,NaN,NaN,NaN,...,37.0,6217.0,142.0,3294.0,19.0,0.0,8.0,9925.0,24.0,1576.0
201906,0,11,676,1,7,1192,NaN,NaN,NaN,NaN,...,38.0,6251.0,146.0,3324.0,19.0,0.0,9.0,10068.0,23.0,1600.0
201907,0,11,690,1,7,1203,NaN,NaN,NaN,NaN,...,39.0,6223.0,150.0,3379.0,19.0,0.0,9.0,9987.0,23.0,1623.0
201908,0,11,696,1,7,1217,NaN,NaN,NaN,NaN,...,78.0,12440.0,304.0,6788.0,19.0,0.0,9.0,10055.0,24.0,1634.0
201909,0,11,689,1,7,1233,NaN,NaN,NaN,NaN,...,38.0,6217.0,161.0,3432.0,19.0,0.0,9.0,10067.0,24.0,1672.0
201910,0,12,693,1,7,1230,NaN,NaN,NaN,NaN,...,41.0,6203.0,163.0,3467.0,20.0,0.0,9.0,10043.0,24.0,1683.0
201911,0,12,695,1,6,1234,NaN,NaN,NaN,NaN,...,42.0,6169.0,163.0,3492.0,18.0,0.0,9.0,9994.0,27.0,1734.0
201912,0,12,693,1,6,1225,NaN,NaN,NaN,NaN,...,41.0,6099.0,159.0,3482.0,16.0,0.0,9.0,9946.0,26.0,1766.0
202001,0,12,689,1,6,1234,NaN,NaN,NaN,NaN,...,42.0,5989.0,155.0,3540.0,14.0,0.0,9.0,9845.0,26.0,1735.0